---
- name: Update RHEL Hostname
  hosts: "{{ target_host_name }}*"
  gather_facts: no
  
  tasks:
  - name: update hostname
    hostname:
      # The variable name is sourced from dynamic inventory variable
      name: "{{ name }}"

  - name: unconditionally reboot the machine with all defaults
    reboot:

  - name: wait for ansible connection
    wait_for_connection:
      timeout: 300  
...